package:
  name: ko
  version: latest
  description: A tool for building and deploying Golang applications to Kubernetes
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - go
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/google/ko.git
    tag: v0.9.3
- runs: export KO_DOCKER_REPO=ko.local
- uses: go/build
  with:
    packages: ./cmd/app
    output: ko
