package:
  name: ko
  version: latest
  description: A simple, fast container image builder for Go applications
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - go
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/google/ko.git
    tag: v0.9.3
- uses: go/build
  with:
    packages: .
    output: ko
