package:
  name: buildkitd
  version: 0.12.3
  description: An extensible framework that enables building container images in a
    reliable and efficient manner.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/moby/buildkit
    tag: v0.12.3
- runs: make binaries
- runs: make install
