package:
  name: buildkitd
  version: 0.12.3
  description: An open-source toolkit for performing complex builds and integrating
    container security features.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/moby/buildkit
    tag: v0.12.3
- uses: go/build
  with:
    packages: .
    output: buildkitd
    modroot: buildkit
    prefix: /usr/local
    install_dir: bin
