package:
  name: guac
  version: 0.3.0
  description: This software project provides VNC support for the Guacamole proxy
    through the libguac-client-vnc plugin using libvncclient.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
    - goreleaser
    - go
    - busybox
    - ca-certificates-bundle
    - jq
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/guacsec/guac
    tag: main
- runs: |
    make
    install -Dm755 ./bin/guaccollect /usr/bin
