package:
  name: zarf
  version: 0.30.1
  description: An application built to manage the deployment of complex applications
    into air-gapped (offline) Kubernetes clusters through a combination of images,
    OS packages, and Kubernetes resources in one package.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - go
      - nodejs

pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/defenseunicorns/zarf
    tag: v0.30.1
- runs: |
    make build-ui
- uses: go/build
  with:
    packages: .
    output: zarf
