package:
  name: aws-load-balancer-controller
  version: 2.6.1
  description: A Kubernetes controller for managing Elastic Load Balancers that works
    within an AWS environment.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/kubernetes-sigs/aws-load-balancer-controller
    tag: v2.6.1
- runs: make controller
- runs: make install
