package:
  name: aws-load-balancer-controller
  version: 2.6.1
  description: "A controller to manage Elastic Load Balancers for a Kubernetes cluster,\
    \ handling Application Load Balancers and Network Load Balancers, developed by\
    \ SIG-AWS\u301027\u2020source\u3011."
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
    - go
    - ca-certificates-bundle
    - busybox
    - bash

pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/kubernetes-sigs/aws-load-balancer-controller
    tag: v2.6.1
- runs: go mod tidy
- uses: go/build
  with:
    packages: main.go
    output: controller
