package:
  name: zarf
  version: 0.30.1
  epoch: 0
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/defenseunicorns/zarf
      expected-commit: 785c5a0f7cf3ce178eeb19b2395ebf5131b043e3
      tag: v${{package.version}}

  - runs: |
      echo ${{targets.destdir}}
      mkdir -p ${{targets.destdir}}/usr/bin/
      make build-ui
      go build -o ${{targets.destdir}}/usr/bin/zarf -ldflags="-s -w -X 'github.com/defenseunicorns/zarf/src/config.CLIVersion=$(git describe --tags)'" .

  - uses: strip

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
