package:
  name: hugo-extended
  version: 0.119.0
  description: Provides a plug-and-play binary wrapper for Hugo Extended, enabling
    easy use of the static-site generator.
  copyright:
  - license: MIT
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/jakejarvis/hugo-extended
    tag: v0.119.0
- runs: npm install
