package:
  name: hugo-extended
  version: 0.119.0
  description: An NPM module that acts as a plug-and-play binary wrapper for Hugo
    Extended, simplifying Hugo integration into Node.js environments.
  copyright:
  - license: MIT
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/jakejarvis/hugo-extended
    tag: v0.119.0
- runs: npm install hugo-extended --save-dev
