package:
  name: zarf
  version: 0.30.1
  description: Zarf is designed to manage Kubernetes applications across air-gapped
    (disconnected) environments using a packaging strategy to support DevSecOps.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/defenseunicorns/zarf
    tag: v0.30.1
- runs: make build
