package:
  name: ko
  version: 0.15.0
  description: A simple, fast container image builder for Go applications that compiles
    Go binaries using `go build` and does not require Docker.
  copyright:
  - license: Apache License 2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/google/ko
    tag: v0.15.0
- uses: go/build
  with:
    packages: .
    output: ko
    modroot: cmd/ko/
