package:
  name: buildkitd
  version: 0.12.3
  description: "concurrent, cache-efficient, and Dockerfile-agnostic builder toolkit"
  epoch: 0
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - libseccomp-dev
      - libseccomp-static

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/moby/buildkit
      tag: v${{package.version}}
      expected-commit: 438f47256f0decd64cc96084e22d3357da494c27

  - runs: |
      PKG=github.com/moby/buildkit
      VERSION=$(git describe --match 'v[0-9]*' --dirty='.m' --always --tags)
      REVISION=$(git rev-parse HEAD)$(if ! git diff --no-ext-diff --quiet --exit-code; then echo .m; fi)

      mkdir -p ${{targets.destdir}}/usr/bin
      go build \
        -ldflags "-s -w -X ${PKG}/version.Version=${VERSION} -X ${PKG}/version.Revision=${REVISION} -X ${PKG}/version.Package=${PKG} -extldflags '-static'" \
        -tags "osusergo netgo static_build seccomp" \
        -o ${{targets.destdir}}/usr/bin/buildkitd ./cmd/buildkitd

      go build \
        -ldflags "-s -w -X ${PKG}/version.Version=${VERSION} -X ${PKG}/version.Revision=${REVISION} -X ${PKG}/version.Package=${PKG} -extldflags '-static'" \
        -o ${{targets.destdir}}/usr/bin/buildctl ./cmd/buildctl

      # https://github.com/moby/buildkit/blob/4c93208b9db9f8936b17c33bc93d19fc1bbf5266/Dockerfile#L152
      cp ./examples/buildctl-daemonless/buildctl-daemonless.sh ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: buildctl
    description: "buildkit client"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/buildctl ${{targets.subpkgdir}}/usr/bin/buildctl
      - uses: strip

update:
  enabled: true
  github:
    identifier: moby/buildkit
    strip-prefix: v
    use-tag: true
    tag-filter: v
