package:
  name: helm
  version: 3.13.1
  epoch: 1
  description: The Kubernetes Package Manager
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helm/helm
      tag: v${{package.version}}
      expected-commit: 3547a4b5bf5edb5478ce352e18858d8a552a4110
      destination: helm

  - runs: |
      cd helm
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build
      install -Dm755 ./bin/helm "${{targets.destdir}}/usr/bin/helm"

  - uses: strip

update:
  enabled: true
  github:
    identifier: helm/helm
    strip-prefix: v
