package:
  name: helm
  version: latest
  description: Helm is a package manager for Kubernetes
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - git
    - go
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/helm/helm
- uses: go/build
  with:
    packages: ./...
    output: helm
