package:
  name: kind
  version: 0.20.0
  description: A tool for running local Kubernetes clusters using Docker container
    'nodes'.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/kubernetes-sigs/kind
    tag: v0.20.0
- uses: go/build
  with:
    packages: ./...
    output: kind
    modroot: kind
- runs: mv kind /usr/local/bin
