package:
  name: kind
  version: 0.20.0
  description: A Kubernetes IN Docker - local clusters for testing Kubernetes.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/kubernetes-sigs/kind
    tag: v0.20.0
- runs: make build
