package:
  name: hugo-extended
  version: 0.119.0
  description: A binary wrapper for Hugo Extended that can be used as a Node dependency
    for easy installation and execution.
  copyright:
  - license: MIT
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/jakejarvis/hugo-extended
    tag: v0.119.0
- runs: npm install hugo-extended --save-dev
