package:
  name: hugo-extended
  version: 0.119.0
  description: A binary wrapper for Hugo Extended to aid in static site generation.
  copyright:
  - license: MIT License
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/jakejarvis/hugo-extended
    tag: v0.119.0
- runs: npm install hugo-extended@0.119.0 --save-dev
