package:
  name: aws-load-balancer-controller
  version: 2.6.1
  description: A Kubernetes controller for managing Elastic Load Balancers.
  copyright:
  - license: "Apache License 2.0\u301043\u2020source\u3011"
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/kubernetes-sigs/aws-load-balancer-controller
    tag: v2.6.1
- runs: make controller
- runs: make install
