package:
  name: helm
  version: 3.13.1
  description: Helm is a tool for managing Charts, which are packages of pre-configured
    Kubernetes resources.
  copyright:
  - license: Apache License 2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/helm/helm
    tag: v3.13.1
- runs: make build
- runs: mv bin/helm /usr/local/bin/helm
