package:
  name: kind
  version: 0.20.0
  description: A tool for running local Kubernetes clusters using Docker container
    'nodes' designed for testing Kubernetes itself, but may be used for local development
    or CI.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/kubernetes-sigs/kind
    tag: v0.20.0
- runs: make build
- runs: make install
