package:
  name: ko
  version: 0.15.0
  description: A tool for building container images for Go applications without requiring
    Docker and minimal dependencies on the OS base image.
  copyright:
  - license: Apache-2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/google/ko
    tag: v0.15.0
- uses: go/build
  with:
    packages: .
    output: ko
    modroot: cmd/ko/
- runs: mv cmd/ko/ko /usr/local/bin/
