package:
  name: aws-load-balancer-controller
  version: 2.6.1
  epoch: 3
  description: A Kubernetes controller for Elastic Load Balancers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-load-balancer-controller
      tag: v${{package.version}}
      expected-commit: 5a5885bfbd3c7237ac190859fe0f20e96c95f1f2

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      # https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/Dockerfile#L18-L27
      VERSION_PKG=sigs.k8s.io/aws-load-balancer-controller/pkg/version
      GIT_VERSION=$(git describe --tags --dirty --always) && \
      GIT_COMMIT=$(git rev-parse HEAD) && \
      BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) && \
      GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) GO111MODULE=on \
      CGO_CPPFLAGS="-D_FORTIFY_SOURCE=2" \
      CGO_LDFLAGS="-Wl,-z,relro,-z,now" \
      go build -buildmode=pie -tags 'osusergo,netgo,static_build' -ldflags="-s -w -linkmode=external -extldflags '-static-pie' -X ${VERSION_PKG}.GitVersion=${GIT_VERSION} -X ${VERSION_PKG}.GitCommit=${GIT_COMMIT} -X ${VERSION_PKG}.BuildDate=${BUILD_DATE}" -mod=readonly -a -o /home/build/out/controller main.go

  - runs: |
      install -Dm755 /home/build/out/controller "${{targets.destdir}}"/usr/bin/controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/aws-load-balancer-controller
    strip-prefix: v
    tag-filter: v
    use-tag: true
