package:
  name: grype
  version: 0.72.0
  epoch: 0
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/anchore/grype/archive/v${{package.version}}/grype-${{package.version}}.tar.gz
      expected-sha512: 8335de5cba0b11500df1404afeee311be50c7e55d1a57c85cbebe830c9e8d9d21ff7b35ab6110200e57f464e999576f395814a56485115f8c7ed7b6e9f7dafb9

  # Update go.mod files, which are apparently stale in the 0.66.0 release
  - runs: |
      go mod tidy

  - runs: |
      CGO_ENABLED=0 go build \
        -ldflags "-w -X github.com/anchore/grype/internal/version.version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/grype" ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v
