package:
  name: helm
  version: 3.13.1
  description: A tool for managing Kubernetes applications, allowing users to manage
    Charts, which are packages of pre-configured Kubernetes resources.
  copyright:
  - license: Apache License 2.0
environment:
  contents:
    packages:
    - wolfi-base
    - build-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/helm/helm
    tag: v3.13.1
- runs: make build-cross
- runs: make dist
- uses: go/build
  with:
    packages: .
    output: helm
    ldflags: -X helm.sh/helm/v3/internal/version.gitCommit=<<GIT_COMMIT>> -X helm.sh/helm/v3/internal/version.gitTreeState=clean
    modroot: path/to/helm/source
    prefix: /usr/local
    install_dir: bin
